tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "xz"
brew "carthage"
brew "cocoapods", link: false
brew "coreutils"
brew "ffmpeg"
brew "git-lfs"
brew "imagemagick"
brew "nmap"
brew "rbenv"
brew "rbenv-gemset"
brew "swiftlint"
brew "thefuck"
brew "wget"
cask "fastlane"
