#!/bin/bash

TARGET_BRANCHES="(master|develop)"

BRANCH="$(git symbolic-ref HEAD 2>/dev/null)" || \
       "$(git describe --contains --all HEAD)"

if [[ "${BRANCH##refs/heads/}" =~ $TARGET_BRANCHES ]]; then
  echo "😇😇😇${branch##refs/heads/}にcommit奴〜〜〜😇😇😇"
  afplay $GIT_DIR/hooks/*.mp3
  exit 1
fi
