#!/bin/bash

TARGET_BRANCHES="(master|develop)"

branch="$(git symbolic-ref HEAD 2>/dev/null)" || \
       "$(git describe --contains --all HEAD)"

if [[ "${branch##refs/heads/}" =~ $TARGET_BRANCHES ]]; then
  echo "😇😇😇${branch##refs/heads/}にcommit奴〜〜〜😇😇😇"
  exit 1
fi
